services:
  pg:
    image: postgres
    container_name: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crud_customer
    networks:
      - server
  app:
    image: node:lts
    container_name: cadastro-arquitetos-server
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    expose:
      - 9000
    ports:
      - 9000:9000
    command: "yarn dev"
    env_file:
      - ./env/.env.dev
    depends_on:
      - pg
    networks:
      - server
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 64M
networks:
  server:
    name: server
    driver: bridge
